image: php:7.3

variables:
  COMPOSER_HOME: .composer
cache:
  paths:
  - .composer

before_script:
- apt-get update && apt-get install -yq unzip
# Install composer dependencies
- curl --silent https://composer.github.io/installer.sig | tr -d '\n' > installer.sig
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
- php composer-setup.php
- php -r "unlink('composer-setup.php'); unlink('installer.sig');"
- rm -rf vendor
- php composer.phar install

stages:
  - test

lint:
  stage: test
  script:
    - bin/php-cs-fixer fix --allow-risky=yes --verbose --dry-run

test:
  stage: test
  script:
    - php composer.phar test -- -f pretty
